version: "3"
services:
    authservice:
        build:
            dockerfile: docker/auth-docker
            context: ..
        restart: always
        depends_on: 
            - db
        networks: 
            - db
            - proxy
        expose: 
            - "80"
    userservice:
        build:
            dockerfile: docker/user-docker
            context: ..
        depends_on: 
            - db
        networks:
            - db
            - proxy
        restart: always
        expose: 
            - "80"
    products:
        build:
            dockerfile: docker/product-docker
            context: ..
        depends_on: 
            - db
        networks:
            - db
            - proxy
        expose: 
            - "80"
        restart: always
    inventory:
        build:
            dockerfile: docker/inventory-docker
            context: ..
        depends_on: 
            - db
        networks:
            - db
            - proxy
        expose: 
            - "80"
        restart: always
    recipe:
        build:
            dockerfile: docker/recipe-docker
            context: ..
        depends_on: 
            - db
        networks:
            - db
            - proxy
        expose: 
            - "80"
        restart: always
    wishlist:
        build:
            dockerfile: docker/wishlist-docker
            context: ..
        depends_on: 
            - db
        networks:
            - db
            - proxy
        expose: 
            - "80"
        restart: always
    shopping:
        build:
            dockerfile: docker/shopping-docker
            context: ..
        depends_on: 
            - db
        networks:
            - db
            - proxy
        expose: 
            - "80"
        restart: always
    frontend:
        build:
            dockerfile: ../KitchenApp/docker/front-docker
            context: ../../Website
        depends_on: 
            - nginx
        networks:
            - proxy
        ports: 
            - 5000:5000
        restart: always
    db:
        build:
            dockerfile: db-docker
            context: .
        expose: 
            - "7687"
            - "7474"
        ports: 
            - 7687:7687
            - 7474:7474
        networks:
            - db
        restart: always
    nginx:
        build: 
            dockerfile: nginx-docker
            context: .
        ports:
            - 1331:80
        depends_on:
            - authservice
            - userservice
            - inventory
            - wishlist
            - shopping
        networks:
            - proxy
        restart: always

networks: 
    db:
    proxy:
